on: push

jobs:
  CICD:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: Rscript {0}
    container:
      # this needs to be the same as in Dockerfile
      image: subugoe/muggle-onbuild:2e75e10fc82b4c5cad586c6b6fef8b23d1b0ff04
    steps:
      - uses: actions/checkout@v2
      - name: Cache R Packages
        uses: actions/cache@v2
        with:
          # only cache the user library
          path: ".github/library"
          key: ${{ job.container.image }}-${{ hashFiles('DESCRIPTION') }}
      - name: Install Azure CLI
        # nonstandard muggle, duplicated in dockerfile
        # TODO remove this https://github.com/subugoe/shinycaas/issues/32
        run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        shell: bash
      - name: Log in to Azure
        uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Install System Dependencies
        run: muggle::install_sysdeps()
      - name: Install R Dependencies
        env:
          # see builder.Dockerfile for explanation, this resets after this step
          R_LIBS_SITE: $R_LIBS_APP_GH
        run: remotes::install_deps(dependencies = TRUE)
      - name: Check
        run: muggle::rcmdcheck2()
      - name: Test Coverage
        run: covr::codecov()
      - name: Build Package Website
        run: pkgdown::build_site(override = list(new_process = FALSE))
      - uses: docker/build-push-action@v1
        name: Build Dev Image
        with:
          repository: ${{ github.repository }}/shinycaas-dev
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          # this will set "latest" if master as per https://github.com/docker/build-push-action
          tag_with_ref: true
          # we're relying on long shas only to keep things easy
          tag_with_sha: false
          tags: ${{ github.sha }}
          add_git_labels: true
          push: ${{ github.event_name != 'pull_request' }}
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: maxheld83/ghpages@github-token
        env:
          BUILD_DIR: docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
